---
title: "SF_climate"
author: "Yingfei Jiang"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lubridate)
library(ggthemes)

```

```{r}

SF_Climate_raw <- read_csv("SF Climate.csv")

SF_Climate <- SF_Climate_raw %>% 
  mutate(DATE_new = ymd(DATE)) %>% 
  mutate(YEAR = year(DATE_new)) %>% 
  mutate(MONTH = month(DATE_new)) %>% 
  mutate(YEARMONTH = floor_date(DATE_new, "year"))

```

```{r}

Tmax_plot <- ggplot(SF_Climate, aes(x = DATE_new, y = TMAX))+
  geom_line()

Tmax_plot

```

```{r}

Tmin_plot <- ggplot(SF_Climate, aes(x = DATE_new, y = TMIN))+
  geom_line()

Tmin_plot

```

```{r}

prcp_plot <- ggplot(SF_Climate, aes(x = DATE_new, y = PRCP))+
  geom_line()

prcp_plot

```

```{r}

SF_under32_raw <- SF_Climate %>% 
  filter(YEAR <= 2018) %>% 
  select(YEARMONTH, TMIN) %>%
  mutate(YEAR = year(YEARMONTH)) %>% 
  filter(TMIN <= 32)

SF_under32 <- aggregate(TMIN ~ YEAR, data = SF_under32_raw, length)

under32_plot <- ggplot(SF_under32, aes(x = YEAR, y = TMIN))+
  geom_point(color = "dark blue")+
  theme_stata()+
  xlab("Year")+
  ylab("Frost Days")+
  scale_x_continuous(breaks = seq(1945, 2020, 5), limits = c(1945, 2020))+
  scale_y_continuous(breaks = seq(0, 20, 5), limits = c(0, 20))

under32_plot

```

```{r}

SF_TN10P_raw <- SF_Climate %>% 
  filter(YEAR <= 2018) %>% 
  select(YEARMONTH, TMIN) %>%
  mutate(YEAR = year(YEARMONTH)) %>% 
  filter(TMIN <= 41)

SF_TN10P <- aggregate(TMIN ~ YEAR, data = SF_TN10P_raw, length)

TN10P_plot <- ggplot(SF_TN10P, aes(x = YEAR, y = TMIN))+
  geom_point(color = "blue")+
  theme_stata()+
  xlab("Year")+
  ylab("Cold Nights")+
  scale_x_continuous(breaks = seq(1945, 2020, 5), limits = c(1945, 2020))+
  scale_y_continuous(breaks = seq(0, 100, 25), limits = c(0, 100))+
  stat_smooth(method = "lm", col = "blue")

TN10P_plot

ggsave("TN10P.png")

res_TN10P=lm(TMIN~YEAR, data=SF_TN10P)
summary(res_TN10P)

```

```{r}

SF_TX90P_raw <- SF_Climate %>% 
  filter(YEAR <= 2018) %>% 
  select(YEARMONTH, TMAX) %>%
  mutate(YEAR = year(YEARMONTH)) %>% 
  filter(TMAX >= 76)

SF_TX90P <- aggregate(TMAX ~ YEAR, data = SF_TX90P_raw, length)

TX90P_plot <- ggplot(SF_TX90P, aes(x = YEAR, y = TMAX))+
  geom_point(color = "red")+
  theme_stata()+
  xlab("Year")+
  ylab("Warm Days")+
  scale_x_continuous(breaks = seq(1945, 2020, 5), limits = c(1945, 2020))+
  scale_y_continuous(breaks = seq(0, 100, 25), limits = c(0, 100))+
  stat_smooth(method = "lm", col = "red")

TX90P_plot

ggsave("TX90P.png")

res_TX90P=lm(TMAX~YEAR, data=SF_TX90P)
summary(res_TX90P)

```

```{r}

SF_TXx_raw <- SF_Climate %>% 
  filter(YEAR <= 2018) %>% 
  select(YEARMONTH, TMAX) %>% 
  mutate(YEAR = year(YEARMONTH))

SF_TXx <- aggregate(TMAX ~ YEAR, data = SF_TXx_raw, max)

TXx_plot <- ggplot(SF_TXx, aes(x = YEAR, y = TMAX))+
  geom_point(color = "red")+
  theme_stata()+
  xlab("Year")+
  ylab("Temperature (F)")+
  scale_x_continuous(breaks = seq(1945, 2020, 5), limits = c(1945, 2020))+
  scale_y_continuous(breaks = seq(85, 110, 5), limits = c(85, 110))+
  stat_smooth(method = "lm", col = "red")

TXx_plot
ggsave("TXx.png")

res_TXx=lm(TMAX~YEAR, data=SF_TXx)
summary(res_TXx)

```

```{r}

SF_TNn_raw <- SF_Climate %>% 
  filter(YEAR <= 2018) %>% 
  select(YEARMONTH, TMIN) %>% 
  mutate(YEAR = year(YEARMONTH))

SF_TNn <- aggregate(TMIN ~ YEAR, data = SF_TNn_raw, min)

TNn_plot <- ggplot(SF_TNn, aes(x = YEAR, y = TMIN))+
  geom_point(color = "blue")+
  theme_stata()+
  xlab("Year")+
  ylab("Temperature (F)")+
  scale_x_continuous(breaks = seq(1945, 2020, 5), limits = c(1945, 2020))+
  scale_y_continuous(breaks = seq(20, 45, 5), limits = c(20, 45))+
  stat_smooth(method = "lm", col = "blue")

TNn_plot
ggsave("TNn.png")

res_TNn=lm(TMIN~YEAR, data=SF_TNn)
summary(res_TNn)

```

```{r}
# sea level rise trends

searise = read_csv("sf_searise.csv")

searise_msl = searise %>% 
  select(Year, Month, Monthly_MSL) %>% 
  filter(Monthly_MSL != "NA")

searise_plot = ggplot(searise_msl, aes(x = Year, y = Monthly_MSL)) +
  geom_line(color = "blue") +
  xlab("Year") +
  ylab("Sea level rise (mm)") +
  ggtitle("Monthly Sea Level Rise in San Francisco") + 
  theme_stata()

searise_plot


```


```{r}

# t-test for sea level rise

searise_1855 = searise_msl %>% 
  filter(Year == "1855")

searise_2018 = searise_msl %>% 
  filter(Year == "2018")

searise_ttest = t.test(searise_1855$Monthly_MSL, searise_2018$Monthly_MSL)
searise_ttest

```


